# Generated by Django 4.2.7 on 2023-12-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_location_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.FloatField()),
                ('yp', models.FloatField()),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
